### ISSUE TITLE
I can Run Hello_World Using Kotlin and Java_17 But I can't run CoroutinesExample

### ISSUE THREAD

**Issue by neuberfran** [Pi4J/pi4j-kotlin#12]
Hi,

I have Rpi4 8gb with Java-17.0.11
I can run a hello world remotely in Kotlin but I get the error below when I try to run the CoroutinesExample example from github

```
[main] INFO com.pi4j.util.Console - 
[main] WARN com.pi4j.library.pigpio.impl.PiGpioNativeImpl - PIGPIO ERROR: PI_INIT_FAILED; pigpio initialisation failed
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy1/jdk.proxy1.$Proxy20.create(Unknown Source)
	at com.pi4j.context.Context.create(Context.java:317)
	at com.pi4j.internal.IOCreator.create(IOCreator.java:58)
	at com.pi4j.internal.IOCreator.create(IOCreator.java:106)
	at MinimalExampleKt.main(MinimalExample.kt:159)
	at MinimalExampleKt.main(MinimalExample.kt)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.pi4j.provider.impl.ProviderProxyHandler.invoke(ProviderProxyHandler.java:100)
	... 6 more
Caused by: com.pi4j.library.pigpio.PiGpioException: PIGPIO ERROR: PI_INIT_FAILED; pigpio initialisation failed
	at com.pi4j.library.pigpio.impl.PiGpioBase.validateResult(PiGpioBase.java:265)
	at com.pi4j.library.pigpio.impl.PiGpioBase.validateResult(PiGpioBase.java:251)
	at com.pi4j.library.pigpio.impl.PiGpioNativeImpl.gpioInitialise(PiGpioNativeImpl.java:98)
	at com.pi4j.library.pigpio.PiGpio.initialize(PiGpio.java:159)
	at com.pi4j.plugin.pigpio.provider.gpio.digital.PiGpioDigitalInputProviderImpl.create(PiGpioDigitalInputProviderImpl.java:60)
	at com.pi4j.plugin.pigpio.provider.gpio.digital.PiGpioDigitalInputProviderImpl.create(PiGpioDigitalInputProviderImpl.java:41)
	... 11 more

Process finished with exit code 1
```
I can't put java_11 in rpi4 
![Captura de tela 2024-07-17 225436](https://github.com/user-attachments/assets/e152bcf6-cc1d-4aca-b817-61e82ddc50c0)

**Comment by neuberfran** [comment]
@FDelporte

**Comment by FDelporte** [comment]
Should not be related to the Java version, I even use Java 22 with Pi4J...

**Comment by FDelporte** [comment]
Did you use this Kotlin DSL? https://www.pi4j.com/kotlin/
@mhashim6 the DSL probably needs an update to newer Pi4J dependencies...

**Comment by mhashim6** [comment]
Thanks for reporting this. Will investigate and make a fix/ release

**Comment by neuberfran** [comment]
@FDelporte 

```
implementation("com.pi4j:pi4j-ktx:2.4.0") // Kotlin DSL
implementation("com.pi4j:pi4j-core:2.3.0")
implementation("com.pi4j:pi4j-plugin-raspberrypi:2.3.0")
implementation("com.pi4j:pi4j-plugin-pigpio:2.3.0")
```
I put all these things in every build.gradle.kts I found in the package I pulled from github and I still get the errors

2) In the future I will have to add things from Firestore, as I am migrating the Android Things project to here. I hope I have more luck
Tks for everything

**Comment by FDelporte** [comment]
Trying out myself but not succeeding yet... @mhashim6 hope you can find some time to review this...

**Comment by FDelporte** [comment]
Success! ;-)

What I did
* checkout this project on a RPi 5
* with sdkman: `sdk install gradle` and `sdk install kotlin`
* opened directory in visual studio code and installed kotlin and gradle extensions
* change dependencies in the project to Pi4J 2.6.0 and slf4j 2.0.12
* added the new plugin dependency `com.pi4j:pi4j-plugin-gpiod`
* in the code, removed the 'piGpioProvider()' because v2.6 of Pi4J automatically loads the provider which is best for the version of the RPi Pi4J is running on
* start the test app with Gradle run

https://github.com/user-attachments/assets/4524f1e6-e3ae-420d-9306-928d28461f39

**Comment by mhashim6** [comment]
@FDelporte really appreciate it. I'm publishing the release rn.

Apologies I didn't have the time

**Comment by FDelporte** [comment]
@mhashim6 no problem! this is a pet project for all of us :-)
not sure if the Kotlin plugin itself needs more updates, can you do a quick check please?

**Comment by FDelporte** [comment]
@mhashim6 we have a V2.6.1 ready for release, so that would require a new update of this Kotlin library. Maybe we should wait a bit till this is released?

**Comment by mhashim6** [comment]
> @mhashim6 we have a V2.6.1 ready for release, so that would require a new update of this Kotlin library. Maybe we should wait a bit till this is released?

It should be no problem, right now I'm working on fixing the tests as some mocks have become now interfaces instead of classes in 2.6.0 :)

I would not release 2.6.0, will wait for your signal.

**Comment by FDelporte** [comment]
Thanks, I just commited some fixes for unit tests and moved library version definition to the root level...

**Comment by mhashim6** [comment]
> Thanks, I just commited some fixes for unit tests and moved library version definition to the root level...

@FDelporte I'm curious why is the AutoContext not automatically detecting mocks? Even though it seems to auto pick other platforms/ providers like the `gpiod`

**Comment by FDelporte** [comment]
@eitch @taartspi good remark above by @mhashim6. Indeed AutoContext on non-RPi indeed seems not to load the Mock. Can this be forced are what was the approach envisioned with the recently introduced priorities?

**Comment by neuberfran** [comment]
@FDelporte Tks
https://www.youtube.com/watch?v=YpFe7AQj29o
1) I am interested in learning more about Cli commands:
sdk install gradle, sdk install kotlin and gradle run
2) I heard that Kotlin's LSP is purposely bad (jetbrains wants to protect its IDE). So it would be bad to use neovim/vscode/kotlin

**Comment by FDelporte** [comment]
I'm happy you also got it working! 

1. SDKMAN: https://foojay.io/today/installing-java-with-sdkman-on-raspberry-pi/
2. I don't know about that, but this was the first time I tried out Kotlin in VSC myself and found it very easy.
